### get_all_persons
GET http://localhost:3001/api/persons

### get_info
GET http://localhost:3001/info

### get_one_person
GET http://localhost:3001/api/persons/2

### delete_person
DELETE  http://localhost:3001/api/persons/2

### add_person
POST http://localhost:3001/api/persons 
content-type: application/json

{
  "name": "mstflotfy",
  "number": "02333"
}
