### get_all_persons
GET http://localhost:3001/api/persons

### get_info
GET http://localhost:3001/info

### get_one_person
GET http://localhost:3001/api/persons/660735ebaa91a246d084720e

### delete_person
DELETE  http://localhost:3001/api/persons/660735ebaa91a246d084720e

### add_person
POST http://localhost:3001/api/persons 
content-type: application/json

{
  "name": "testPerson",
  "number": "123"
}

### update_person
PUT http://localhost:3001/api/persons/660c6fd2714a9a034ff9fab4
content-type: application/json

{
  "name": "mstflotfy",
  "number": "00000000"
}

### unkown_endpoint
GET http://localhost:3001/hello